@startuml uml

left to right direction

package "fr.enseirb_matmeca.p220_iabied_nabrouk_wamine"{

    package "logic"{

        interface BasicObject{

            + {static} BasicObject buildBasicObject(String type, ArrayList<String> paramList) \n\t throws IllegalArgumentException

            + boolean isValid()

        }

        class Id implements BasicObject{

            - int value
            - boolean isValid

            + Id(int value) 
            + Id(ArrayList<String> paramList)
            + boolean isValid()
            + int getId()

        }

        class Number implements BasicObject{

            - int value
            - boolean isValid

            + Number(int value)
            + Number(ArrayList<String> paramList)
            + boolean isValid()
            + int getNumber()

        }

        class Price implements BasicObject {

            - Double value
            - boolean isValid

            + Price(Double value)
            + Price(ArrayList<String> paramList)
            + boolean isValid()
            + Double getPrice()

        }


        abstract class Actor {

            + Id getId()

        }
        Actor *-- Id
        
    }

}